CREATE TABLE UserDeviceInfo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    deviceInfo VARCHAR(255) NOT NULL,
    imei VARCHAR(255) NOT NULL,
    phoneNumber VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    submissionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
